spring.application.name=auth.service
spring.datasource.url=jdbc:mysql://localhost:3306/auth_services
spring.datasource.username=root
spring.datasource.password=Nishank@014
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port = 8081

